config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'products/new'
    get 'products/edit'
    get 'products/show'
    get 'products/index'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  root 'products#index'
  devise_for :users

  resources :users, only: %i[index show]

  resources :charges
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user&.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 99999 }
  validates :description, length: { maximum: 1000 }
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def index
    @products = Product.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart

  def current_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  def index
    @cart_items = CartItem.all
  end

  def show
  end

  def new
    @cart_item = CartItem.new
  end

  def edit
  end

  def create
    @cart_item = current_cart

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    def cart_item_params
      params.fetch(:cart_item, {})
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: %i(add_item update_item delete_item)

  def show
    @cart_items = current_cart.cart_items
  end


  def add_item
    if @cart_item.blank?
      @cart_item = current_cart.cart_items.build(product_id, params[:product_id])
    end

    @cart_item.quantity += params[:quantity].to_i
    @cart_item.save
    redirect_to current_cart
  end


  def update_item
    @cart_item.update(quantity: params[:quantity].to_i)
    redirect_to current_cart
  end


  def delete_item
    @cart_item.destroy
    redirect_to current_cart
  end

  private

  def setup_cart_item!
    @cart_item = current_cart.cart_items.find_by(product_id, params[:product_id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'うまいさかな',
      currency: 'jpy'
    )
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: '商品を追加しました' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: '商品を更新しました' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.image.purge if @product.image.attached?
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '商品を削除しました' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:email)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/edit.html.haml
%h1 Admin::Products#edit
%p Find me in app/views/admin/products/edit.html.haml

app/views/admin/products/index.html.haml
%h1 Admin::Products#index
%p Find me in app/views/admin/products/index.html.haml

app/views/admin/products/new.html.haml
%h1 Admin::Products#new
%p Find me in app/views/admin/products/new.html.haml

app/views/admin/products/show.html.haml
%h1 Admin::Products#show
%p Find me in app/views/admin/products/show.html.haml

app/views/cart_items/_form.html.haml
= form_for @cart_item do |f|
  - if @cart_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart_item.errors.count, "error")} prohibited this cart_item from being saved:"
      %ul
        - @cart_item.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/cart_items/edit.html.haml
%h1 Editing cart_item

= render 'form'

= link_to 'Show', @cart_item
\|
= link_to 'Back', cart_items_path

app/views/cart_items/index.html.haml
%h1 Listing cart_items

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @cart_items.each do |cart_item|
      %tr
        %td= link_to 'Show', cart_item
        %td= link_to 'Edit', edit_cart_item_path(cart_item)
        %td= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Cart item', new_cart_item_path

app/views/cart_items/new.html.haml
%h1 New cart_item

= render 'form'

= link_to 'Back', cart_items_path

app/views/cart_items/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_cart_item_path(@cart_item)
\|
= link_to 'Back', cart_items_path

app/views/charges/create.html.haml
%h2
  Thanks, you paid $5.00

app/views/charges/new.html.haml
= form_tag charges_path do
  %article
    - if flash[:error].present?
      #error_explanation
        %p = flash[:error]
    %label.amount
      %span Amount: ￥500


  = javascript_include_tag "https://checkout.stripe.com/checkout.js", |
    class:"stripe-button", |
    data: { |
      key: "#{Rails.application.credentials.dig(:stripe, :publishable_key)}", |
      description: "高級な🐟", |
      image: "https://stripe.com/img/documentation/checkout/marketplace.png", |
      label: "カードで支払う", |
      name: "さくらま", |
      amount: "500", |
      locale: "ja", |
      currency: "jpy", |
      panel: { label: "500円のお支払い" }}

app/views/homes/index.html.haml
%h1 さくらまへようこそ

app/views/products/_form.html.haml
- if @product.errors.present?
  %ul#error_explanation
    - @product.errors.full_messages.each do |message|
      %li= message

= form_for @product do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :price
    = f.number_field :price, class: 'form-control'
  .form-group
    = f.label :image
    = f.file_field :image
  .form-group
    = f.label :description
    = f.text_field :description, row: 5, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 商品の編集

= render 'form'

= link_to '詳細', @product
\|
= link_to '戻る', products_path

app/views/products/index.html.haml
%h1 商品一覧


.card-deck
  - @products.each do |product|
    .card{style: "width: 20rem;"}
      - if product.image.attached?
        %img.card-img-top{ src: url_for(product.image) }
      .card-body
        %h4.card-title #{product.name} #{product.price}
        %p.card-text
          = product.description
      .card-footer
        %p.card-text
          = link_to '詳細', product, class: "btn btn-primary"
          = link_to '編集', edit_product_path(product), class: "btn btn-default"
          = link_to '削除', product, method: :delete, data: { confirm: 'よろしいですか？' }, class: "btn btn-danger"
%br

= link_to '新規商品', new_product_path

app/views/products/new.html.haml
%h1 新規商品

= render 'form'

= link_to '戻る', products_path

app/views/products/show.html.haml
%h1 商品の詳細

.nav.justify-content-end
  = link_to '一覧', products_path, class: 'nav-link'
  = link_to '編集', edit_product_path(@product), class: 'nav-link'
%table.table.table-hover
  %tbody
    %tr
      %th= Product.human_attribute_name(:name)
      %td= @product.name
    %tr
      %th= Product.human_attribute_name(:price)
      %td= @product.price
    %tr
      %th= Product.human_attribute_name(:image)
      %td
        - if @product.image.attached?
          =image_tag url_for(@product.image), style: "width: 20rem;"
        - else
          画像がありません
    %tr
      %th= Product.human_attribute_name(:description)
      %td= @product.description

app/views/users/index.html.haml
%ul.list-group
- @users.each do |user|
  %li.list-group-item= link_to user.email, user_path(user)